/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pomofocus;

/**
 *
 * @author putur
 */
public class TambahTujuan extends javax.swing.JFrame {

    /**
     * Creates new form TambahTujuan
     */
    public TambahTujuan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        JudulTugasTambah = new javax.swing.JTextField();
        DeadlineTugasTambah = new com.toedter.calendar.JDateChooser();
        WaktuTanggalDeadline = new javax.swing.JLabel();
        WaktuTanggalDeadline1 = new javax.swing.JLabel();
        WaktuTanggalDeadline2 = new javax.swing.JLabel();
        WaktuTanggalDeadline3 = new javax.swing.JLabel();
        PanelAtas2 = new javax.swing.JPanel();
        JudulTugas1 = new javax.swing.JLabel();
        button1 = new pomofocus.Button();
        WaktuDeadlineTugasTambah = new lu.tudor.santec.jtimechooser.JTimeChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(248, 244, 225));
        MainPanel.setPreferredSize(new java.awt.Dimension(375, 812));

        JudulTugasTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JudulTugasTambahActionPerformed(evt);
            }
        });

        WaktuTanggalDeadline.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WaktuTanggalDeadline.setForeground(new java.awt.Color(0, 0, 153));
        WaktuTanggalDeadline.setText("Waktu Tujuan");

        WaktuTanggalDeadline1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WaktuTanggalDeadline1.setForeground(new java.awt.Color(0, 0, 153));
        WaktuTanggalDeadline1.setText("Judul Tujuan");

        WaktuTanggalDeadline2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WaktuTanggalDeadline2.setForeground(new java.awt.Color(0, 0, 153));
        WaktuTanggalDeadline2.setText("Pilih Tanggal");

        WaktuTanggalDeadline3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WaktuTanggalDeadline3.setForeground(new java.awt.Color(0, 0, 153));

        PanelAtas2.setBackground(new java.awt.Color(255, 174, 57));
        PanelAtas2.setForeground(new java.awt.Color(102, 0, 102));

        JudulTugas1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JudulTugas1.setForeground(new java.awt.Color(0, 0, 153));
        JudulTugas1.setText("Tambah Tujuan");

        javax.swing.GroupLayout PanelAtas2Layout = new javax.swing.GroupLayout(PanelAtas2);
        PanelAtas2.setLayout(PanelAtas2Layout);
        PanelAtas2Layout.setHorizontalGroup(
            PanelAtas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtas2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(JudulTugas1)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        PanelAtas2Layout.setVerticalGroup(
            PanelAtas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAtas2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(JudulTugas1)
                .addGap(40, 40, 40))
        );

        button1.setText("Simpan Tujuan");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAtas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WaktuDeadlineTugasTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JudulTugasTambah)
                                    .addComponent(DeadlineTugasTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                                .addComponent(WaktuTanggalDeadline, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(WaktuTanggalDeadline1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(WaktuTanggalDeadline2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(WaktuTanggalDeadline3)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addComponent(PanelAtas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(WaktuTanggalDeadline1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JudulTugasTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WaktuTanggalDeadline2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeadlineTugasTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(WaktuTanggalDeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WaktuDeadlineTugasTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WaktuTanggalDeadline3)
                .addGap(88, 88, 88)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        
    }//GEN-LAST:event_button1ActionPerformed

    private void JudulTugasTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JudulTugasTambahActionPerformed

    }//GEN-LAST:event_JudulTugasTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahTujuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahTujuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahTujuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahTujuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahTujuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DeadlineTugasTambah;
    private javax.swing.JLabel JudulTugas1;
    private javax.swing.JTextField JudulTugasTambah;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelAtas2;
    private lu.tudor.santec.jtimechooser.JTimeChooser WaktuDeadlineTugasTambah;
    private javax.swing.JLabel WaktuTanggalDeadline;
    private javax.swing.JLabel WaktuTanggalDeadline1;
    private javax.swing.JLabel WaktuTanggalDeadline2;
    private javax.swing.JLabel WaktuTanggalDeadline3;
    private pomofocus.Button button1;
    // End of variables declaration//GEN-END:variables
}
